[package]
name = "tetris-rs"
version = "0.1.0"
edition = "2021"
authors = ["Hyejin Lee <genie4cs@gmail.com>"]
repository = "https://github.com/genieCS/tetris-rs"

[dependencies]
cursive = "0.20"
rand = "0.8.4"